version: 2

updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
    time: "05:00" # 5AM UTC

- package-ecosystem: npm
  directory: /client
  registries:
    - npm
  schedule:
    interval: daily
    time: "05:00" # 5AM UTC
  open-pull-requests-limit: 5
