version: 2

updates:

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /client
  registries:
    - npm
  schedule:
    interval: daily
  open-pull-requests-limit: 5

- package-ecosystem: docker
  directory: /api
  schedule:
    interval: daily

- package-ecosystem: npm
  directory: /api
  registries:
    - npm
  schedule:
    interval: daily
  open-pull-requests-limit: 5
