/* tslint:disable */
/* eslint-disable */
/**
 * PGA Pool API
 * The API for PGA Pool
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface GetWeeklyField404Response
 */
export interface GetWeeklyField404Response {
    /**
     * The HTTP status code
     * @type {number}
     * @memberof GetWeeklyField404Response
     */
    'status': number;
    /**
     * The error response code
     * @type {string}
     * @memberof GetWeeklyField404Response
     */
    'message': string;
    /**
     * Additional detail about the error
     * @type {string}
     * @memberof GetWeeklyField404Response
     */
    'detail'?: string | null;
}
/**
 * 
 * @export
 * @interface LimitOffsetResponseMeta
 */
export interface LimitOffsetResponseMeta {
    /**
     * 
     * @type {LimitOffsetResponseMetaPage}
     * @memberof LimitOffsetResponseMeta
     */
    'page': LimitOffsetResponseMetaPage;
}
/**
 * 
 * @export
 * @interface LimitOffsetResponseMetaPage
 */
export interface LimitOffsetResponseMetaPage {
    /**
     * Requested page size.
     * @type {number}
     * @memberof LimitOffsetResponseMetaPage
     */
    'requested_size': number;
    /**
     * Specifies the actual size of the page returned.
     * @type {number}
     * @memberof LimitOffsetResponseMetaPage
     */
    'actual_size': number;
    /**
     * Specifies the current page number (1-based index).
     * @type {number}
     * @memberof LimitOffsetResponseMetaPage
     */
    'number': number;
    /**
     * Total amount of items.
     * @type {number}
     * @memberof LimitOffsetResponseMetaPage
     */
    'total'?: number;
}
/**
 * 
 * @export
 * @interface List200Response
 */
export interface List200Response {
    /**
     * 
     * @type {Array<PoolTournament>}
     * @memberof List200Response
     */
    'data': Array<PoolTournament>;
}
/**
 * 
 * @export
 * @interface ListPgaPlayers200Response
 */
export interface ListPgaPlayers200Response {
    /**
     * 
     * @type {LimitOffsetResponseMeta}
     * @memberof ListPgaPlayers200Response
     */
    'meta': LimitOffsetResponseMeta;
    /**
     * 
     * @type {Array<PgaPlayer>}
     * @memberof ListPgaPlayers200Response
     */
    'data': Array<PgaPlayer>;
}
/**
 * 
 * @export
 * @interface ListPgaPlayersFilterParameter
 */
export interface ListPgaPlayersFilterParameter {
    /**
     * Case-insensitive partial match on player name
     * @type {string}
     * @memberof ListPgaPlayersFilterParameter
     */
    'name'?: string;
    /**
     * Filter by active status (defaults to true if not specified)
     * @type {boolean}
     * @memberof ListPgaPlayersFilterParameter
     */
    'active'?: boolean;
}
/**
 * 
 * @export
 * @interface ListPgaPlayersPageParameter
 */
export interface ListPgaPlayersPageParameter {
    /**
     * The number of items included per page.
     * @type {number}
     * @memberof ListPgaPlayersPageParameter
     */
    'size'?: number;
    /**
     * The specific page number (1-based) of the collection results.
     * @type {number}
     * @memberof ListPgaPlayersPageParameter
     */
    'number'?: number;
}
/**
 * 
 * @export
 * @interface ListPgaTournamentPlayers200Response
 */
export interface ListPgaTournamentPlayers200Response {
    /**
     * 
     * @type {LimitOffsetResponseMeta}
     * @memberof ListPgaTournamentPlayers200Response
     */
    'meta': LimitOffsetResponseMeta;
    /**
     * 
     * @type {Array<PgaTournamentPlayer>}
     * @memberof ListPgaTournamentPlayers200Response
     */
    'data': Array<PgaTournamentPlayer>;
}
/**
 * 
 * @export
 * @interface ListPgaTournaments200Response
 */
export interface ListPgaTournaments200Response {
    /**
     * 
     * @type {LimitOffsetResponseMeta}
     * @memberof ListPgaTournaments200Response
     */
    'meta': LimitOffsetResponseMeta;
    /**
     * 
     * @type {Array<PgaTournament>}
     * @memberof ListPgaTournaments200Response
     */
    'data': Array<PgaTournament>;
}
/**
 * 
 * @export
 * @interface ListPgaTournamentsFilterParameter
 */
export interface ListPgaTournamentsFilterParameter {
    /**
     * 
     * @type {string}
     * @memberof ListPgaTournamentsFilterParameter
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof ListPgaTournamentsFilterParameter
     */
    'date.year'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListPgaTournamentsFilterParameter
     */
    'fedex_cup_event'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ListPgaTournamentsFilterParameter
     */
    'scoring_format'?: string;
    /**
     * 
     * @type {string}
     * @memberof ListPgaTournamentsFilterParameter
     */
    'tournament_status'?: string;
}
/**
 * Defines a PGA player (i.e. golfer)
 * @export
 * @interface PgaPlayer
 */
export interface PgaPlayer {
    /**
     * 
     * @type {number}
     * @memberof PgaPlayer
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PgaPlayer
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PgaPlayer
     */
    'short_name': string;
    /**
     * 
     * @type {string}
     * @memberof PgaPlayer
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof PgaPlayer
     */
    'last_name': string;
    /**
     * 
     * @type {boolean}
     * @memberof PgaPlayer
     */
    'active': boolean;
    /**
     * 
     * @type {string}
     * @memberof PgaPlayer
     */
    'headshot_url': string | null;
}
/**
 * Defines a PGA tournament event
 * @export
 * @interface PgaTournament
 */
export interface PgaTournament {
    /**
     * ID in the format of \"{tournamentId}-{year}\"
     * @type {string}
     * @memberof PgaTournament
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'name': string;
    /**
     * 
     * @type {TournamentDate}
     * @memberof PgaTournament
     */
    'date': TournamentDate;
    /**
     * 
     * @type {number}
     * @memberof PgaTournament
     */
    'purse': number;
    /**
     * 
     * @type {number}
     * @memberof PgaTournament
     */
    'fedex_cup_points': number | null;
    /**
     * 
     * @type {boolean}
     * @memberof PgaTournament
     */
    'fedex_cup_event': boolean;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'scoring_format': PgaTournamentScoringFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'tournament_status': PgaTournamentTournamentStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'round_status': PgaTournamentRoundStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PgaTournament
     */
    'current_round': number | null;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'course_name': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'country_code': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'state_code': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'city': string;
    /**
     * 
     * @type {PgaTournamentPreviousChampion}
     * @memberof PgaTournament
     */
    'previous_champion': PgaTournamentPreviousChampion;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'logo_url': string | null;
    /**
     * 
     * @type {string}
     * @memberof PgaTournament
     */
    'course_image_url': string | null;
}

export const PgaTournamentScoringFormatEnum = {
    StrokePlay: 'STROKE_PLAY',
    TeamStroke: 'TEAM_STROKE',
    Stableford: 'STABLEFORD'
} as const;

export type PgaTournamentScoringFormatEnum = typeof PgaTournamentScoringFormatEnum[keyof typeof PgaTournamentScoringFormatEnum];
export const PgaTournamentTournamentStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED'
} as const;

export type PgaTournamentTournamentStatusEnum = typeof PgaTournamentTournamentStatusEnum[keyof typeof PgaTournamentTournamentStatusEnum];
export const PgaTournamentRoundStatusEnum = {
    Upcoming: 'UPCOMING',
    GroupingsOfficial: 'GROUPINGS_OFFICIAL',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Official: 'OFFICIAL'
} as const;

export type PgaTournamentRoundStatusEnum = typeof PgaTournamentRoundStatusEnum[keyof typeof PgaTournamentRoundStatusEnum];

/**
 * The PGA Tournament player field divided into tiers.
 * @export
 * @interface PgaTournamentField
 */
export interface PgaTournamentField {
    /**
     * 
     * @type {PgaTournament}
     * @memberof PgaTournamentField
     */
    'pga_tournament': PgaTournament;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentField
     */
    'created_at': string;
    /**
     * 
     * @type {{ [key: string]: Array<PgaTournamentFieldPlayerTiersValueInner>; }}
     * @memberof PgaTournamentField
     */
    'player_tiers': { [key: string]: Array<PgaTournamentFieldPlayerTiersValueInner>; };
}
/**
 * 
 * @export
 * @interface PgaTournamentFieldPlayerTiersValueInner
 */
export interface PgaTournamentFieldPlayerTiersValueInner {
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentFieldPlayerTiersValueInner
     */
    'player_id': number;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentFieldPlayerTiersValueInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentFieldPlayerTiersValueInner
     */
    'odds': string;
}
/**
 * Defines a PGA player participating in a PGA tournament
 * @export
 * @interface PgaTournamentPlayer
 */
export interface PgaTournamentPlayer {
    /**
     * ID in the format of {pgaPlayerId}-{pgaTournamentId}
     * @type {string}
     * @memberof PgaTournamentPlayer
     */
    'id': string;
    /**
     * 
     * @type {boolean}
     * @memberof PgaTournamentPlayer
     */
    'active': boolean;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentPlayer
     */
    'status': PgaTournamentPlayerStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PgaTournamentPlayer
     */
    'is_round_complete': boolean;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'current_round': number | null;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'current_hole': number;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'starting_hole': number;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentPlayer
     */
    'tee_time': string | null;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'score_total': number;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'score_thru': number | null;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentPlayer
     */
    'current_position': string | null;
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPlayer
     */
    'projected_fedex_cup_points'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PgaTournamentPlayer
     */
    'withdrawn': boolean;
    /**
     * 
     * @type {PgaPlayer}
     * @memberof PgaTournamentPlayer
     */
    'pga_player': PgaPlayer;
    /**
     * 
     * @type {PgaTournament}
     * @memberof PgaTournamentPlayer
     */
    'pga_tournament': PgaTournament;
}

export const PgaTournamentPlayerStatusEnum = {
    Active: 'active',
    Complete: 'complete',
    Wd: 'wd',
    Cut: 'cut'
} as const;

export type PgaTournamentPlayerStatusEnum = typeof PgaTournamentPlayerStatusEnum[keyof typeof PgaTournamentPlayerStatusEnum];

/**
 * 
 * @export
 * @interface PgaTournamentPreviousChampion
 */
export interface PgaTournamentPreviousChampion {
    /**
     * 
     * @type {number}
     * @memberof PgaTournamentPreviousChampion
     */
    'id': number | null;
    /**
     * 
     * @type {string}
     * @memberof PgaTournamentPreviousChampion
     */
    'name': string | null;
}
/**
 * Defines a pool tournament
 * @export
 * @interface PoolTournament
 */
export interface PoolTournament {
    /**
     * 
     * @type {string}
     * @memberof PoolTournament
     */
    'id': string;
    /**
     * Whether the pool tournament is currently live
     * @type {boolean}
     * @memberof PoolTournament
     */
    'active': boolean;
    /**
     * 
     * @type {PgaTournament}
     * @memberof PoolTournament
     */
    'pga_tournament': PgaTournament;
    /**
     * 
     * @type {Array<PoolUser>}
     * @memberof PoolTournament
     */
    'pool_users': Array<PoolUser>;
}
/**
 * Defines a pool user
 * @export
 * @interface PoolUser
 */
export interface PoolUser {
    /**
     * 
     * @type {string}
     * @memberof PoolUser
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof PoolUser
     */
    'score': number;
    /**
     * 
     * @type {number}
     * @memberof PoolUser
     */
    'projected_fedex_cup_points'?: number | null;
    /**
     * 
     * @type {User}
     * @memberof PoolUser
     */
    'user': User;
    /**
     * 
     * @type {Array<PgaTournamentPlayer>}
     * @memberof PoolUser
     */
    'picks': Array<PgaTournamentPlayer>;
}
/**
 * Defines a tournament date
 * @export
 * @interface TournamentDate
 */
export interface TournamentDate {
    /**
     * 
     * @type {number}
     * @memberof TournamentDate
     */
    'year': number;
    /**
     * 
     * @type {string}
     * @memberof TournamentDate
     */
    'start': string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDate
     */
    'end': string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDate
     */
    'timezone': string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDate
     */
    'display': string;
    /**
     * 
     * @type {string}
     * @memberof TournamentDate
     */
    'display_short': string;
}
/**
 * Defines a user (i.e. contestant who competes in pools)
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'nickname': string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email': string | null;
}
/**
 * The PGA Tournament player field for the current week, divided into tiers.
 * @export
 * @interface WeeklyPgaTournamentField
 */
export interface WeeklyPgaTournamentField {
    /**
     * 
     * @type {PgaTournament}
     * @memberof WeeklyPgaTournamentField
     */
    'pga_tournament': PgaTournament;
    /**
     * 
     * @type {string}
     * @memberof WeeklyPgaTournamentField
     */
    'created_at': string | null;
    /**
     * 
     * @type {{ [key: string]: Array<PgaTournamentFieldPlayerTiersValueInner>; }}
     * @memberof WeeklyPgaTournamentField
     */
    'player_tiers': { [key: string]: Array<PgaTournamentFieldPlayerTiersValueInner>; } | null;
}

/**
 * PGAPlayersApi - axios parameter creator
 * @export
 */
export const PGAPlayersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lists PGA Players. Returns only active players by default.
         * @summary Lists PGA Players
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {ListPgaPlayersFilterParameter} [filter] Filters a collection of PGA Players.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaPlayers: async (page?: ListPgaPlayersPageParameter, filter?: ListPgaPlayersFilterParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pga-players`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PGAPlayersApi - functional programming interface
 * @export
 */
export const PGAPlayersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PGAPlayersApiAxiosParamCreator(configuration)
    return {
        /**
         * Lists PGA Players. Returns only active players by default.
         * @summary Lists PGA Players
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {ListPgaPlayersFilterParameter} [filter] Filters a collection of PGA Players.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPgaPlayers(page?: ListPgaPlayersPageParameter, filter?: ListPgaPlayersFilterParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPgaPlayers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPgaPlayers(page, filter, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PGAPlayersApi.listPgaPlayers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PGAPlayersApi - factory interface
 * @export
 */
export const PGAPlayersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PGAPlayersApiFp(configuration)
    return {
        /**
         * Lists PGA Players. Returns only active players by default.
         * @summary Lists PGA Players
         * @param {PGAPlayersApiListPgaPlayersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaPlayers(requestParameters: PGAPlayersApiListPgaPlayersRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListPgaPlayers200Response> {
            return localVarFp.listPgaPlayers(requestParameters.page, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listPgaPlayers operation in PGAPlayersApi.
 * @export
 * @interface PGAPlayersApiListPgaPlayersRequest
 */
export interface PGAPlayersApiListPgaPlayersRequest {
    /**
     * 
     * @type {ListPgaPlayersPageParameter}
     * @memberof PGAPlayersApiListPgaPlayers
     */
    readonly page?: ListPgaPlayersPageParameter

    /**
     * Filters a collection of PGA Players.
     * @type {ListPgaPlayersFilterParameter}
     * @memberof PGAPlayersApiListPgaPlayers
     */
    readonly filter?: ListPgaPlayersFilterParameter
}

/**
 * PGAPlayersApi - object-oriented interface
 * @export
 * @class PGAPlayersApi
 * @extends {BaseAPI}
 */
export class PGAPlayersApi extends BaseAPI {
    /**
     * Lists PGA Players. Returns only active players by default.
     * @summary Lists PGA Players
     * @param {PGAPlayersApiListPgaPlayersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PGAPlayersApi
     */
    public listPgaPlayers(requestParameters: PGAPlayersApiListPgaPlayersRequest = {}, options?: RawAxiosRequestConfig) {
        return PGAPlayersApiFp(this.configuration).listPgaPlayers(requestParameters.page, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PGATournamentPlayersApi - axios parameter creator
 * @export
 */
export const PGATournamentPlayersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lists players for a given PGA Tournament
         * @summary Lists players for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaTournamentPlayers: async (pgaTournamentId: string, page?: ListPgaPlayersPageParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgaTournamentId' is not null or undefined
            assertParamExists('listPgaTournamentPlayers', 'pgaTournamentId', pgaTournamentId)
            const localVarPath = `/pga-tournaments/{pgaTournamentId}/players`
                .replace(`{${"pgaTournamentId"}}`, encodeURIComponent(String(pgaTournamentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PGATournamentPlayersApi - functional programming interface
 * @export
 */
export const PGATournamentPlayersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PGATournamentPlayersApiAxiosParamCreator(configuration)
    return {
        /**
         * Lists players for a given PGA Tournament
         * @summary Lists players for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPgaTournamentPlayers(pgaTournamentId: string, page?: ListPgaPlayersPageParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPgaTournamentPlayers200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPgaTournamentPlayers(pgaTournamentId, page, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PGATournamentPlayersApi.listPgaTournamentPlayers']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PGATournamentPlayersApi - factory interface
 * @export
 */
export const PGATournamentPlayersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PGATournamentPlayersApiFp(configuration)
    return {
        /**
         * Lists players for a given PGA Tournament
         * @summary Lists players for a given PGA Tournament
         * @param {PGATournamentPlayersApiListPgaTournamentPlayersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaTournamentPlayers(requestParameters: PGATournamentPlayersApiListPgaTournamentPlayersRequest, options?: RawAxiosRequestConfig): AxiosPromise<ListPgaTournamentPlayers200Response> {
            return localVarFp.listPgaTournamentPlayers(requestParameters.pgaTournamentId, requestParameters.page, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listPgaTournamentPlayers operation in PGATournamentPlayersApi.
 * @export
 * @interface PGATournamentPlayersApiListPgaTournamentPlayersRequest
 */
export interface PGATournamentPlayersApiListPgaTournamentPlayersRequest {
    /**
     * 
     * @type {string}
     * @memberof PGATournamentPlayersApiListPgaTournamentPlayers
     */
    readonly pgaTournamentId: string

    /**
     * 
     * @type {ListPgaPlayersPageParameter}
     * @memberof PGATournamentPlayersApiListPgaTournamentPlayers
     */
    readonly page?: ListPgaPlayersPageParameter
}

/**
 * PGATournamentPlayersApi - object-oriented interface
 * @export
 * @class PGATournamentPlayersApi
 * @extends {BaseAPI}
 */
export class PGATournamentPlayersApi extends BaseAPI {
    /**
     * Lists players for a given PGA Tournament
     * @summary Lists players for a given PGA Tournament
     * @param {PGATournamentPlayersApiListPgaTournamentPlayersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PGATournamentPlayersApi
     */
    public listPgaTournamentPlayers(requestParameters: PGATournamentPlayersApiListPgaTournamentPlayersRequest, options?: RawAxiosRequestConfig) {
        return PGATournamentPlayersApiFp(this.configuration).listPgaTournamentPlayers(requestParameters.pgaTournamentId, requestParameters.page, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PGATournamentsApi - axios parameter creator
 * @export
 */
export const PGATournamentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getField: async (pgaTournamentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgaTournamentId' is not null or undefined
            assertParamExists('getField', 'pgaTournamentId', pgaTournamentId)
            const localVarPath = `/pga-tournaments/{pgaTournamentId}/field`
                .replace(`{${"pgaTournamentId"}}`, encodeURIComponent(String(pgaTournamentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyField: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pga-tournaments/weekly-field`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Lists PGA Tournaments
         * @summary Lists PGA Tournaments
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {ListPgaTournamentsFilterParameter} [filter] Filters a collection of PGA Tournaments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaTournaments: async (page?: ListPgaPlayersPageParameter, filter?: ListPgaTournamentsFilterParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pga-tournaments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PGATournamentsApi - functional programming interface
 * @export
 */
export const PGATournamentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PGATournamentsApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getField(pgaTournamentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PgaTournamentField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getField(pgaTournamentId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PGATournamentsApi.getField']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeeklyField(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WeeklyPgaTournamentField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeeklyField(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PGATournamentsApi.getWeeklyField']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Lists PGA Tournaments
         * @summary Lists PGA Tournaments
         * @param {ListPgaPlayersPageParameter} [page] 
         * @param {ListPgaTournamentsFilterParameter} [filter] Filters a collection of PGA Tournaments.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPgaTournaments(page?: ListPgaPlayersPageParameter, filter?: ListPgaTournamentsFilterParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPgaTournaments200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPgaTournaments(page, filter, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PGATournamentsApi.listPgaTournaments']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PGATournamentsApi - factory interface
 * @export
 */
export const PGATournamentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PGATournamentsApiFp(configuration)
    return {
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {PGATournamentsApiGetFieldRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getField(requestParameters: PGATournamentsApiGetFieldRequest, options?: RawAxiosRequestConfig): AxiosPromise<PgaTournamentField> {
            return localVarFp.getField(requestParameters.pgaTournamentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyField(options?: RawAxiosRequestConfig): AxiosPromise<WeeklyPgaTournamentField> {
            return localVarFp.getWeeklyField(options).then((request) => request(axios, basePath));
        },
        /**
         * Lists PGA Tournaments
         * @summary Lists PGA Tournaments
         * @param {PGATournamentsApiListPgaTournamentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPgaTournaments(requestParameters: PGATournamentsApiListPgaTournamentsRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<ListPgaTournaments200Response> {
            return localVarFp.listPgaTournaments(requestParameters.page, requestParameters.filter, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getField operation in PGATournamentsApi.
 * @export
 * @interface PGATournamentsApiGetFieldRequest
 */
export interface PGATournamentsApiGetFieldRequest {
    /**
     * 
     * @type {string}
     * @memberof PGATournamentsApiGetField
     */
    readonly pgaTournamentId: string
}

/**
 * Request parameters for listPgaTournaments operation in PGATournamentsApi.
 * @export
 * @interface PGATournamentsApiListPgaTournamentsRequest
 */
export interface PGATournamentsApiListPgaTournamentsRequest {
    /**
     * 
     * @type {ListPgaPlayersPageParameter}
     * @memberof PGATournamentsApiListPgaTournaments
     */
    readonly page?: ListPgaPlayersPageParameter

    /**
     * Filters a collection of PGA Tournaments.
     * @type {ListPgaTournamentsFilterParameter}
     * @memberof PGATournamentsApiListPgaTournaments
     */
    readonly filter?: ListPgaTournamentsFilterParameter
}

/**
 * PGATournamentsApi - object-oriented interface
 * @export
 * @class PGATournamentsApi
 * @extends {BaseAPI}
 */
export class PGATournamentsApi extends BaseAPI {
    /**
     * Fetches the tiered player field for a given PGA Tournament
     * @summary Fetches the player field for a given PGA Tournament
     * @param {PGATournamentsApiGetFieldRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PGATournamentsApi
     */
    public getField(requestParameters: PGATournamentsApiGetFieldRequest, options?: RawAxiosRequestConfig) {
        return PGATournamentsApiFp(this.configuration).getField(requestParameters.pgaTournamentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
     * @summary Fetches the player field for the current week\'s tournament
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PGATournamentsApi
     */
    public getWeeklyField(options?: RawAxiosRequestConfig) {
        return PGATournamentsApiFp(this.configuration).getWeeklyField(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Lists PGA Tournaments
     * @summary Lists PGA Tournaments
     * @param {PGATournamentsApiListPgaTournamentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PGATournamentsApi
     */
    public listPgaTournaments(requestParameters: PGATournamentsApiListPgaTournamentsRequest = {}, options?: RawAxiosRequestConfig) {
        return PGATournamentsApiFp(this.configuration).listPgaTournaments(requestParameters.page, requestParameters.filter, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * PoolTournamentApi - axios parameter creator
 * @export
 */
export const PoolTournamentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches a pool tournament by ID
         * @summary Fetches a pool tournament by ID
         * @param {string} poolTournamentId Pool Tournament ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (poolTournamentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'poolTournamentId' is not null or undefined
            assertParamExists('get', 'poolTournamentId', poolTournamentId)
            const localVarPath = `/pool/tournaments/{poolTournamentId}`
                .replace(`{${"poolTournamentId"}}`, encodeURIComponent(String(poolTournamentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetches the current in-progress pool tournament. Responds with 404 if no tournaments are current.
         * @summary Fetches the current in-progress pool tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrent: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pool/tournaments/current`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getField: async (pgaTournamentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pgaTournamentId' is not null or undefined
            assertParamExists('getField', 'pgaTournamentId', pgaTournamentId)
            const localVarPath = `/pga-tournaments/{pgaTournamentId}/field`
                .replace(`{${"pgaTournamentId"}}`, encodeURIComponent(String(pgaTournamentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyField: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pga-tournaments/weekly-field`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns all pool tournaments
         * @summary List pool tournaments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pool/tournaments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PoolTournamentApi - functional programming interface
 * @export
 */
export const PoolTournamentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PoolTournamentApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches a pool tournament by ID
         * @summary Fetches a pool tournament by ID
         * @param {string} poolTournamentId Pool Tournament ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(poolTournamentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PoolTournament>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(poolTournamentId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PoolTournamentApi.get']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Fetches the current in-progress pool tournament. Responds with 404 if no tournaments are current.
         * @summary Fetches the current in-progress pool tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrent(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PoolTournament>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrent(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PoolTournamentApi.getCurrent']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {string} pgaTournamentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getField(pgaTournamentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PgaTournamentField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getField(pgaTournamentId, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PoolTournamentApi.getField']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWeeklyField(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WeeklyPgaTournamentField>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWeeklyField(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PoolTournamentApi.getWeeklyField']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * Returns all pool tournaments
         * @summary List pool tournaments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async list(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<List200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.list(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['PoolTournamentApi.list']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * PoolTournamentApi - factory interface
 * @export
 */
export const PoolTournamentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PoolTournamentApiFp(configuration)
    return {
        /**
         * Fetches a pool tournament by ID
         * @summary Fetches a pool tournament by ID
         * @param {PoolTournamentApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: PoolTournamentApiGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<PoolTournament> {
            return localVarFp.get(requestParameters.poolTournamentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetches the current in-progress pool tournament. Responds with 404 if no tournaments are current.
         * @summary Fetches the current in-progress pool tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrent(options?: RawAxiosRequestConfig): AxiosPromise<PoolTournament> {
            return localVarFp.getCurrent(options).then((request) => request(axios, basePath));
        },
        /**
         * Fetches the tiered player field for a given PGA Tournament
         * @summary Fetches the player field for a given PGA Tournament
         * @param {PoolTournamentApiGetFieldRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getField(requestParameters: PoolTournamentApiGetFieldRequest, options?: RawAxiosRequestConfig): AxiosPromise<PgaTournamentField> {
            return localVarFp.getField(requestParameters.pgaTournamentId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
         * @summary Fetches the player field for the current week\'s tournament
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWeeklyField(options?: RawAxiosRequestConfig): AxiosPromise<WeeklyPgaTournamentField> {
            return localVarFp.getWeeklyField(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns all pool tournaments
         * @summary List pool tournaments
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        list(options?: RawAxiosRequestConfig): AxiosPromise<List200Response> {
            return localVarFp.list(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for get operation in PoolTournamentApi.
 * @export
 * @interface PoolTournamentApiGetRequest
 */
export interface PoolTournamentApiGetRequest {
    /**
     * Pool Tournament ID
     * @type {string}
     * @memberof PoolTournamentApiGet
     */
    readonly poolTournamentId: string
}

/**
 * Request parameters for getField operation in PoolTournamentApi.
 * @export
 * @interface PoolTournamentApiGetFieldRequest
 */
export interface PoolTournamentApiGetFieldRequest {
    /**
     * 
     * @type {string}
     * @memberof PoolTournamentApiGetField
     */
    readonly pgaTournamentId: string
}

/**
 * PoolTournamentApi - object-oriented interface
 * @export
 * @class PoolTournamentApi
 * @extends {BaseAPI}
 */
export class PoolTournamentApi extends BaseAPI {
    /**
     * Fetches a pool tournament by ID
     * @summary Fetches a pool tournament by ID
     * @param {PoolTournamentApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PoolTournamentApi
     */
    public get(requestParameters: PoolTournamentApiGetRequest, options?: RawAxiosRequestConfig) {
        return PoolTournamentApiFp(this.configuration).get(requestParameters.poolTournamentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetches the current in-progress pool tournament. Responds with 404 if no tournaments are current.
     * @summary Fetches the current in-progress pool tournament
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PoolTournamentApi
     */
    public getCurrent(options?: RawAxiosRequestConfig) {
        return PoolTournamentApiFp(this.configuration).getCurrent(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetches the tiered player field for a given PGA Tournament
     * @summary Fetches the player field for a given PGA Tournament
     * @param {PoolTournamentApiGetFieldRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PoolTournamentApi
     */
    public getField(requestParameters: PoolTournamentApiGetFieldRequest, options?: RawAxiosRequestConfig) {
        return PoolTournamentApiFp(this.configuration).getField(requestParameters.pgaTournamentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the tournament field for the current week (Sunday 2AM EST to Sunday 2AM EST). Returns 404 if no tournament is scheduled this week. Returns 200 with player_tiers: null if tournament exists but field data is not yet available. 
     * @summary Fetches the player field for the current week\'s tournament
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PoolTournamentApi
     */
    public getWeeklyField(options?: RawAxiosRequestConfig) {
        return PoolTournamentApiFp(this.configuration).getWeeklyField(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns all pool tournaments
     * @summary List pool tournaments
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PoolTournamentApi
     */
    public list(options?: RawAxiosRequestConfig) {
        return PoolTournamentApiFp(this.configuration).list(options).then((request) => request(this.axios, this.basePath));
    }
}



