version: '3.5'

services:
  postgres:
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgapoolapi
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
